SCREEN_WIDTH = 960
SCREEN_HEIGHT = 600
FPS = 60
MENU_BACKGROUND_COLOR = ((0, 255, 255))

TITLE_X = SCREEN_WIDTH / 2 # SCREEN_WIDTH / 4
TITLE_Y = SCREEN_HEIGHT * 3 / 10
TITLE_SIZE = int(SCREEN_HEIGHT / 6)
TITLE_COLOR = (0, 0, 0)
HINT_X = SCREEN_WIDTH / 2 # SCREEN_WIDTH * 3 / 8
HINT_Y = SCREEN_HEIGHT / 1.5
HINT_SIZE = int(SCREEN_HEIGHT / 12)
HINT_COLOR = (153, 153, 0)

SCROLL_SPEED = 75

HEALTH = 10
SHIP_SPEED = 150 # pixels/segundo
H_POSITION_PLAYER = SCREEN_WIDTH / 8
H_POSITION_ENEMY = SCREEN_WIDTH * 7 / 8
PROJECTILE_SPEED = SCREEN_WIDTH / 2
PROJECTILE_DELAY = 0.5
PROJECTILE_DAMAGE = 1
